name: Continuous Integration (CI)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install system dependencies like gcc, make, etc.
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y libreadline-dev

      # 2) Build your project
      - name: make
        run: make

      # 3) Run tests
      - name: make check
        run: make check
